version: "3.8"

services:
  app:
    build:
      context: ../../../
      dockerfile: dockers/developing/performance/app/Dockerfile
    env_file:
      - ./app/.env
    ports:
      - "3000:3000"
      - "9229:9229"
    depends_on:
      - db

  db:
    image: postgres:14
    env_file:
      - ./db/.env
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
